[package]
name = "fs-private"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile.workspace = true
